export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';

export const VEHICLES_ADD_REQUEST = 'VEHICLES_ADD_REQUEST';
export const VEHICLES_ADD_REQUEST_SUCCESS = 'VEHICLES_ADD_REQUEST_SUCCESS';
export const VEHICLES_ADD_REQUEST_FAILURE = 'VEHICLES_ADD_REQUEST_FAILURE';

export const VEHICLES_FETCH_REQUEST = 'VEHICLES_FETCH_REQUEST';
export const VEHICLES_FETCH_REQUEST_SUCCESS = 'VEHICLES_FETCH_REQUEST_SUCCESS';
export const VEHICLES_FETCH_REQUEST_FAILURE = 'VEHICLES_FETCH_REQUEST_FAILURE';

export const VEHICLES_UPDATE_REQUEST = 'VEHICLES_UPDATE_REQUEST';
export const VEHICLES_UPDATE_REQUEST_SUCCESS = 'VEHICLES_UPDATE_REQUEST_SUCCESS';
export const VEHICLES_UPDATE_REQUEST_FAILURE = 'VEHICLES_UPDATE_REQUEST_FAILURE';

export const VEHICLES_DELETE_REQUEST = 'VEHICLES_DELETE_REQUEST';
export const VEHICLES_DELETE_REQUEST_SUCCESS = 'VEHICLES_DELETE_REQUEST_SUCCESS';
export const VEHICLES_DELETE_REQUEST_FAILURE = 'VEHICLES_DELETE_REQUEST_FAILURE';

export const VEHICLES_CLEAN_REQUEST = 'VEHICLES_CLEAN_REQUEST';

export const INVENTORY_ADD_REQUEST = 'INVENTORY_ADD_REQUEST';
export const INVENTORY_ADD_REQUEST_SUCCESS = 'INVENTORY_ADD_REQUEST_SUCCESS';
export const INVENTORY_ADD_REQUEST_FAILURE = 'INVENTORY_ADD_REQUEST_FAILURE';

export const INVENTORY_FETCH_REQUEST = 'INVENTORY_FETCH_REQUEST';
export const INVENTORY_FETCH_REQUEST_SUCCESS = 'INVENTORY_FETCH_REQUEST_SUCCESS';
export const INVENTORY_FETCH_REQUEST_FAILURE = 'INVENTORY_FETCH_REQUEST_FAILURE';

export const INVENTORY_UPDATE_REQUEST = 'INVENTORY_UPDATE_REQUEST';
export const INVENTORY_UPDATE_REQUEST_SUCCESS = 'INVENTORY_UPDATE_REQUEST_SUCCESS';
export const INVENTORY_UPDATE_REQUEST_FAILURE = 'INVENTORY_UPDATE_REQUEST_FAILURE';

export const INVENTORY_DELETE_REQUEST = 'INVENTORY_DELETE_REQUEST';
export const INVENTORY_DELETE_REQUEST_SUCCESS = 'INVENTORY_DELETE_REQUEST_SUCCESS';
export const INVENTORY_DELETE_REQUEST_FAILURE = 'INVENTORY_DELETE_REQUEST_FAILURE';

export const INVENTORY_CLEAN_REQUEST = 'INVENTORY_CLEAN_REQUEST';

export const TAX_ADD_REQUEST = 'TAX_ADD_REQUEST';
export const TAX_ADD_REQUEST_SUCCESS = 'TAX_ADD_REQUEST_SUCCESS';
export const TAX_ADD_REQUEST_FAILURE = 'TAX_ADD_REQUEST_FAILURE';

export const TAX_FETCH_REQUEST = 'TAX_FETCH_REQUEST';
export const TAX_FETCH_REQUEST_SUCCESS = 'TAX_FETCH_REQUEST_SUCCESS';
export const TAX_FETCH_REQUEST_FAILURE = 'TAX_FETCH_REQUEST_FAILURE';

export const TAX_UPDATE_REQUEST = 'TAX_UPDATE_REQUEST';
export const TAX_UPDATE_REQUEST_SUCCESS = 'TAX_UPDATE_REQUEST_SUCCESS';
export const TAX_UPDATE_REQUEST_FAILURE = 'TAX_UPDATE_REQUEST_FAILURE';

export const TAX_DELETE_REQUEST = 'TAX_DELETE_REQUEST';
export const TAX_DELETE_REQUEST_SUCCESS = 'TAX_DELETE_REQUEST_SUCCESS';
export const TAX_DELETE_REQUEST_FAILURE = 'TAX_DELETE_REQUEST_FAILURE';

export const TAX_CLEAN_REQUEST = 'TAX_CLEAN_REQUEST';

