export const HTTP_404_ERROR = 'HTTP_404_ERROR';
export const HTTP_500_ERROR = 'HTTP_500_ERROR';

export const VEHICLES_ADD_REQUEST = 'VEHICLES_ADD_REQUEST';
export const VEHICLES_ADD_REQUEST_SUCCESS = 'VEHICLES_ADD_REQUEST_SUCCESS';
export const VEHICLES_ADD_REQUEST_FAILURE = 'VEHICLES_ADD_REQUEST_FAILURE';

export const VEHICLES_FETCH_REQUEST = 'VEHICLES_FETCH_REQUEST';
export const VEHICLES_FETCH_REQUEST_SUCCESS = 'VEHICLES_FETCH_REQUEST_SUCCESS';
export const VEHICLES_FETCH_REQUEST_FAILURE = 'VEHICLES_FETCH_REQUEST_FAILURE';

export const VEHICLES_UPDATE_REQUEST = 'VEHICLES_UPDATE_REQUEST';
export const VEHICLES_UPDATE_REQUEST_SUCCESS = 'VEHICLES_UPDATE_REQUEST_SUCCESS';
export const VEHICLES_UPDATE_REQUEST_FAILURE = 'VEHICLES_UPDATE_REQUEST_FAILURE';

export const VEHICLES_DELETE_REQUEST = 'VEHICLES_DELETE_REQUEST';
export const VEHICLES_DELETE_REQUEST_SUCCESS = 'VEHICLES_DELETE_REQUEST_SUCCESS';
export const VEHICLES_DELETE_REQUEST_FAILURE = 'VEHICLES_DELETE_REQUEST_FAILURE';

export const VEHICLES_CLEAN_REQUEST = 'VEHICLES_CLEAN_REQUEST';

